name: Fetch Dish 28hrs to XML

on:
  schedule:
    - cron: '0 11 * * *'  # Se ejecuta a las 11:00 AM UTC = 6:00 AM GMT-5
  workflow_dispatch:

jobs:
  fetch-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium
        pip install requests

    - name: Run EPG fetch script
      run: python fetchdish-28hrs.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push dish.xml
      run: |
        git add dish.xml
        if ! git diff --cached --quiet; then
          git commit -m "Actualizado - [$(TZ=\"America/Cancun\" date +\"%d-%m-%Y %H:%M GMT-5\")] - [$(date +'%d-%m-%Y %H:%M UTC')]"
          git pull --rebase origin main  # Tu adición: sincroniza remotos antes de push
          git push origin main  # Especifica el branch para claridad (en lugar de git push implícito)
        else
          echo "No hay cambios para commitear"
        fi
