name: Fetch EPG with Playwright and Retries

on:
  schedule:
    - cron: '0 2 * * *'  # Ejecuta diariamente a las 2:00 AM UTC
  workflow_dispatch:     # Permite ejecución manual

jobs:
  fetch-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run EPG fetch script with retries
        run: python fetch_epg.py
