name: Fetch detodotv to XML

on:
  schedule:
    - cron: '0 11 * * *'  # Ejecuta a medianoche UTC todos los días
  workflow_dispatch:      # Permite ejecución manual desde GitHub

jobs:
  update-xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Descargar segundo XML
      run: |
        - name: Descargar segundo XML
        curl -v -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -L -o openepg.xml "http://live.detodotvplay.com/xmltv.php?username=Risario8&password=Pineda13"

    - name: Configurar git para push con token personal
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Dingolobo/test.git

    - name: Commit y push cambios
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add openepg.xml
        git commit -m "Actualizar guía EPG procesada" || echo "No hay cambios para commitear"
        git push origin main
