name: Fetch MVSHUB new to XML

on:
  schedule:
    - cron: '0 11 * * *'  # Ejecuta a medianoche UTC todos los días
  workflow_dispatch:      # Permite ejecución manual desde GitHub 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run EPG fetch script
      env:
        TIMEZONE_OFFSET: '0'  # Ajusta si quieres otro offset horario
        CHANNEL_IDS: '208, 482, 487, 613, 885, 737, 746, 748, 765, 804, 805, 882, 981, 982, 606, 1446, 969, 815, 967, 822, 814, 736, 808, 807, 809, 762, 801, 764, 806, 704, 705'  # Opcional, puedes cambiar o pasar por args
      run: |
        python mvshubnew.py
    
    - name: Commit and push XML
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mvshub.xml
        git diff --staged --quiet || git commit -m "Update EPG XMLTV $(date +'%Y-%m-%d')"
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
