name: Fetch API Data

on:
  workflow_dispatch:  # Ejecuta manualmente

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests webdriver-manager

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable  # Instala la versión estable de Chrome

    - name: Run script
      run: python fetch-tubi.py
