name: Fetch Fox Tubi XML
on:
  schedule:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with: { python-version: 3.9 }
    - name: Install dependencies
      run: pip install requests
    - name: Run script
      run: fetch-fox-tubi.py
    - name: Commit XML
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tubi_fox.xml
        git commit -m "Update EPG XML" || exit 0
        git push
