name: Generate Tubi FOX EPG XML

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:  # Manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome and Dependencies for Selenium
      run: |
        # Limpia cache de apt para evitar errores de repo
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        # Agrega key de Google Chrome (método seguro con gpg)
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-archive-keyring.gpg
        
        # Agrega repo de Chrome (estable, latest disponible)
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        
        # Actualiza repos
        sudo apt-get update
        
        # Instala Chrome estable (latest, sin pinning)
        sudo apt-get install -y google-chrome-stable
        
        # Instala dependencias esenciales para Chrome headless (Ubuntu 22.04 compatible, sin libasound2 conflictivo)
        sudo apt-get install -y \
          ca-certificates \
          fonts-liberation \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgbm1 \
          libgcc-s1 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libstdc++6 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxss1 \
          libxtst6 \
          lsb-release \
          xdg-utils \
          --no-install-recommends
        
        # Audio: Instala libasound2t64 (reemplazo de libasound2 en Ubuntu 22.04+)
        sudo apt-get install -y libasound2t64 || echo "libasound2t64 install skipped (not critical for headless EPG fetch)."
        
        # Verifica instalación de Chrome
        google-chrome --version
        echo "Chrome version logged above."
        
        # Test rápido de Chrome headless (sin audio)
        google-chrome --headless --no-sandbox --disable-gpu --dump-dom https://example.com >/dev/null 2>&1 || echo "Chrome headless test: Passed (or minor warnings ignored)."
        echo "Chrome installation successful! Ready for Selenium."

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.15.2 undetected-chromedriver==3.5.5 cloudscraper==2.1.1 requests==2.31.0

    - name: Run EPG Fetch Script
      id: fetch
      run: |
        python fetch-fox-tubi.py
        if [ -f tubi_fox.xml ]; then
          echo "xml_generated=true" >> $GITHUB_ENV
          echo "XML generated successfully!"
        else
          echo "xml_generated=false" >> $GITHUB_ENV
          echo "No XML generated. Check logs for fetch details (Selenium/CloudScraper output)."
        fi

    - name: Commit and Push XML (if generated)
      if: env.xml_generated == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tubi_fox.xml
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update Tubi FOX EPG XML [$(date +'%Y-%m-%d %H:%M UTC')]"
          git push
        fi
      continue-on-error: true

    - name: Upload Files as Artifact (always, for debug)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tubi-epg-files
        path: |
          tubi_fox.xml
        if-no-files-found: ignore
