name: Generate Tubi FOX EPG XML

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies (Chrome for Selenium)
      run: |
        # Instala Chrome y fonts para headless
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends
        # Verifica Chrome
        google-chrome --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium undetected-chromedriver cloudscraper requests  # Selenium principal, fallbacks

    - name: Run EPG Fetch Script
      id: fetch
      run: |
        python fetch-fox-tubi.py
        if [ -f tubi_fox.xml ]; then
          echo "xml_generated=true" >> $GITHUB_ENV
        else
          echo "xml_generated=false" >> $GITHUB_ENV
          echo "No XML (Akamai block?). Check logs for Selenium output."
        fi

    - name: Commit and Push XML (if generated)
      if: env.xml_generated == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tubi_fox.xml
        git diff --staged --quiet || git commit -m "Update Tubi FOX EPG XML [$(date +'%Y-%m-%d %H:%M')]"

        git push
      continue-on-error: true

    - name: Upload XML as Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tubi-epg-xml
        path: tubi_fox.xml
        if-no-files-found: ignore
