name: Generate Tubi FOX EPG XML

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome for Selenium
      run: |
        # Instala Chrome 120+ para undetected-chromedriver
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable=120.0.6099.71-1 libxss1 libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libatspi2.0-0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango-1.0-0 libcairo-gobject2 libasound2 fonts-liberation --no-install-recommends
        google-chrome --version  # Log versión
        # Instala chromedriver si necesario (undetected maneja auto)
        sudo apt-get install -y xvfb  # Para headless display

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install selenium==4.15.2 undetected-chromedriver==3.5.5 cloudscraper==2.1.1 requests==2.31.0

    - name: Run EPG Fetch Script
      run: |
        python fetch-fox-tubi.py
        if [ -f tubi_fox.xml ]; then
          echo "XML generated successfully!"
        else
          echo "No XML generated. Check logs above for Selenium/CloudScraper details."
        fi

    - name: Commit XML if generated
      if: always()
      run: |
        if [ -f tubi_fox.xml ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tubi_fox.xml
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Tubi FOX EPG [$(date +'%Y-%m-%d %H:%M')]"
            git push
          fi
        fi
      continue-on-error: true

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tubi-epg-files
        path: |
          tubi_fox.xml
          *.log  # Si agregas logs
        if-no-files-found: ignore
